# Generated by Django 5.2.2 on 2025-08-02 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('pickup_location', models.CharField(max_length=100, verbose_name='Điểm nhận')),
                ('delivery_location', models.CharField(max_length=100, verbose_name='Điểm giao')),
                ('with_receipt_amount', models.PositiveIntegerField(default=0, verbose_name='Có phiếu (VNĐ)')),
                ('without_receipt_amount', models.PositiveIntegerField(default=0, verbose_name='Không phiếu (VNĐ)')),
                ('cost_type', models.CharField(blank=True, choices=[('fuel', 'Xăng dầu'), ('meal', 'Ăn uống'), ('other', 'Khác')], max_length=20, verbose_name='Loại chi phí')),
                ('allowance', models.PositiveIntegerField(default=0, verbose_name='Phụ cấp')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
