# Generated by Django 5.2.2 on 2025-09-13 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Biển số')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tên xe')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên lái xe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_type', models.CharField(blank=True, choices=[('driver', 'Lái xe'), ('company', 'Công ty')], default='driver', max_length=10, verbose_name='Thực hiện')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('pickup_location', models.CharField(blank=True, max_length=100, verbose_name='Điểm nhận hàng')),
                ('delivery_location', models.CharField(blank=True, max_length=100, verbose_name='Điểm giao hàng')),
                ('with_receipt_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Có phiếu (VNĐ)')),
                ('without_receipt_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Không phiếu (VNĐ)')),
                ('cost_type', models.CharField(blank=True, choices=[('fuel', 'Nhiên liệu'), ('fuel', 'Làm hàng'), ('advance payment', 'Ứng'), ('payment', 'Thu khách'), ('meal', 'Xe nâng'), ('meal', 'Bốc xếp'), ('other', 'Khác')], max_length=20, verbose_name='Loại chi phí')),
                ('allowance', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True)),
                ('km_on_vehicle', models.IntegerField(blank=True, default=0)),
                ('advance_or_customer_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thu khách / Ứng tiền')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_images', to='expenses.expenseentry')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu áp dụng')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc áp dụng')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.vehicle')),
            ],
            options={
                'unique_together': {('driver', 'vehicle', 'start_date')},
            },
        ),
    ]
