# Generated by Django 5.2.2 on 2025-08-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='allowance',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Phụ cấp'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Điểm giao'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Điểm nhận'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='with_receipt_amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Có phiếu (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='without_receipt_amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Không phiếu (VNĐ)'),
        ),
    ]
