# Generated by Django 5.2.2 on 2025-08-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenseentry_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='advance_or_customer_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thu khách / Ứng tiền'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='km_on_vehicle',
            field=models.PositiveIntegerField(default=0, verbose_name='KM trên xe'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='cost_type',
            field=models.CharField(blank=True, choices=[('fuel', 'Làm hàng'), ('meal', 'Xe nâng'), ('meal', 'Bốc xếp'), ('other', 'Khác')], max_length=20, verbose_name='Loại chi phí'),
        ),
    ]
