# Generated by Django 5.2.2 on 2025-08-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenseentry_advance_or_customer_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='cost_type',
            field=models.CharField(blank=True, choices=[('fuel', 'Nhiên liệu'), ('advance payment', 'Ứng'), ('payment', 'Thu khách'), ('meal', 'Xe nâng'), ('meal', 'Bốc xếp'), ('other', 'Khác')], max_length=20, verbose_name='Loại chi phí'),
        ),
    ]
