# Generated by Django 5.2.2 on 2025-08-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expenseentry_cost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='payer_type',
            field=models.CharField(choices=[('driver', 'Lái xe chi'), ('company', 'Công ty chi')], default='driver', max_length=10, verbose_name='Người chi'),
        ),
    ]
