# Generated by Django 5.2.2 on 2025-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expenseentry_payer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='payer_type',
            field=models.CharField(blank=True, choices=[('driver', 'Lái xe'), ('company', 'Công ty')], max_length=10, verbose_name='Thực hiện'),
        ),
    ]
