# Generated by Django 5.2.2 on 2025-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expenseentry_payer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='advance_or_customer_payment',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thu khách / Ứng tiền'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='allowance',
            field=models.PositiveIntegerField(blank=True, verbose_name='Phụ cấp'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='km_on_vehicle',
            field=models.PositiveIntegerField(blank=True, verbose_name='KM trên xe'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='with_receipt_amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Có phiếu (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='without_receipt_amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Không phiếu (VNĐ)'),
        ),
    ]
