# Generated by Django 5.2.2 on 2025-08-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expenseentry_cost_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='payer_type',
            field=models.CharField(blank=True, choices=[('driver', 'Lái xe'), ('company', 'Công ty')], default='driver', max_length=10, verbose_name='Thực hiện'),
        ),
    ]
