# Generated by Django 5.2.2 on 2025-08-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expenseentry_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='km_on_vehicle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
