# Generated by Django 5.2.2 on 2025-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_expenseentry_km_on_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='advance_or_customer_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thu khách / Ứng tiền'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='km_on_vehicle',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
