# Generated by Django 5.2.1 on 2025-08-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_expenseentry_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='with_receipt_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Có phiếu (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='without_receipt_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Không phiếu (VNĐ)'),
        ),
    ]
