# Generated by Django 5.2.1 on 2025-08-04 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_alter_expenseentry_with_receipt_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseentry',
            name='receipt_image',
        ),
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_images', to='expenses.expenseentry')),
            ],
        ),
    ]
