# Generated by Django 5.2.1 on 2025-09-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_remove_expenseentry_receipt_image_receiptimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='driver',
            field=models.CharField(blank=True, choices=[('Phương', 'Phương'), ('Hoàng', 'Hoàng'), ('Quý', 'Quý')], max_length=20, verbose_name='Lái xe'),
        ),
    ]
