# Generated by Django 5.2.1 on 2025-09-05 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_expenseentry_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tài xế')),
                ('name_vehicle', models.CharField(blank=True, max_length=100, verbose_name='Tên xe')),
            ],
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.driver'),
        ),
    ]
