# Generated by Django 5.2.1 on 2025-09-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_driver_alter_expenseentry_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Biển số')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tên xe')),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name_vehicle',
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên lái xe'),
        ),
    ]
