# Generated by Django 5.2.1 on 2025-09-05 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_vehicle_remove_driver_name_vehicle_alter_driver_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu áp dụng')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc áp dụng')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.vehicle')),
            ],
            options={
                'unique_together': {('driver', 'vehicle', 'start_date')},
            },
        ),
    ]
